### ISSUE TITLE
Jacoco로 테스트 커버리지 관리

### ISSUE THREAD

**Issue by dahyen0o** [wootecam-gugucon/shopping-mall#39]
## ✨ 내용

테스트 커버리지를 관리한다.

## 🤷 TO DO

- [ ] Jacoco와 연결
- [ ] CI에 커버리지 제한 조건 추가

## 🧑‍🏫 기타 사항

- 없으면 지우고 제출해주세요

**Comment by dongjoo0-0** [comment]
https://techblog.woowahan.com/2661/
